apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
  labels:
    app: django
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
        - name: django
          image: my-django-app:1.0 # current version
          ports:
            - containerPort: 8000
