apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-green
  labels:
    app: django
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      version: green
  template:
    metadata:
      labels:
        app: django
        version: green
    spec:
      containers:
        - name: django
          image: my-django-app:2.0 # new version
          ports:
            - containerPort: 8000
